# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'nuv14' do

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NailsUnlimitedAppv1

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'React', path: rn_path, subspecs: [
    # 'BatchedBridge',
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS

  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

end
source 'https://github.com/CocoaPods/Specs.git'

#need to turn off for some of the pod installs but turn this shit back on!!!! (frameworks)
use_frameworks!

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
